//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilingHostService.EFMFilingReviewService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0", ConfigurationName="EFMFilingReviewService.FilingReviewMDEService")]
    public interface FilingReviewMDEService {
        
        // CODEGEN: Generating message contract since element name ReviewFilingRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/ReviewFiling", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/ReviewFilingResponse")]
        FilingHostService.EFMFilingReviewService.ReviewFilingResponse ReviewFiling(FilingHostService.EFMFilingReviewService.ReviewFilingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/ReviewFiling", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/ReviewFilingResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.ReviewFilingResponse> ReviewFilingAsync(FilingHostService.EFMFilingReviewService.ReviewFilingRequest request);
        
        // CODEGEN: Generating message contract since element name NotifyDocketingCompleteRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyDocketingComplete", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyDocketingCompleteResponse")]
        FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponse NotifyDocketingComplete(FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyDocketingComplete", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyDocketingCompleteResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponse> NotifyDocketingCompleteAsync(FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest request);
        
        // CODEGEN: Generating message contract since element name NotifyCaseAssignmentCompleteRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyCaseAssignmentComplete", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyCaseAssignmentCompleteResponse")]
        FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponse NotifyCaseAssignmentComplete(FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyCaseAssignmentComplete", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/NotifyCaseAssignmentCompleteResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponse> NotifyCaseAssignmentCompleteAsync(FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest request);
        
        // CODEGEN: Generating message contract since element name GetFeesCalculationRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFeesCalculation", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFeesCalculationResponse")]
        FilingHostService.EFMFilingReviewService.GetFeesCalculationResponse GetFeesCalculation(FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFeesCalculation", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFeesCalculationResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFeesCalculationResponse> GetFeesCalculationAsync(FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest request);
        
        // CODEGEN: Generating message contract since element name GetFilingListRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingList", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingListResponse")]
        FilingHostService.EFMFilingReviewService.GetFilingListResponse GetFilingList(FilingHostService.EFMFilingReviewService.GetFilingListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingList", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingListResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingListResponse> GetFilingListAsync(FilingHostService.EFMFilingReviewService.GetFilingListRequest request);
        
        // CODEGEN: Generating message contract since element name GetFilingStatusRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingStatus", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingStatusResponse")]
        FilingHostService.EFMFilingReviewService.GetFilingStatusResponse GetFilingStatus(FilingHostService.EFMFilingReviewService.GetFilingStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingStatus", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingStatusResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingStatusResponse> GetFilingStatusAsync(FilingHostService.EFMFilingReviewService.GetFilingStatusRequest request);
        
        // CODEGEN: Generating message contract since element name GetPolicyRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetPolicy", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetPolicyResponse")]
        FilingHostService.EFMFilingReviewService.GetPolicyResponse GetPolicy(FilingHostService.EFMFilingReviewService.GetPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetPolicy", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetPolicyResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetPolicyResponse> GetPolicyAsync(FilingHostService.EFMFilingReviewService.GetPolicyRequest request);
        
        // CODEGEN: Generating message contract since element name GetFilingDetailsRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingDetails", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingDetailsResponse")]
        FilingHostService.EFMFilingReviewService.GetFilingDetailsResponse GetFilingDetails(FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingDetails", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingDetailsResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingDetailsResponse> GetFilingDetailsAsync(FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetFilingServiceRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingService", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingServiceResponse")]
        FilingHostService.EFMFilingReviewService.GetFilingServiceResponse GetFilingService(FilingHostService.EFMFilingReviewService.GetFilingServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingService", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/GetFilingServiceResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingServiceResponse> GetFilingServiceAsync(FilingHostService.EFMFilingReviewService.GetFilingServiceRequest request);
        
        // CODEGEN: Generating message contract since element name CancelFilingRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/CancelFiling", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/CancelFilingResponse")]
        FilingHostService.EFMFilingReviewService.CancelFilingResponse CancelFiling(FilingHostService.EFMFilingReviewService.CancelFilingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/CancelFiling", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/CancelFilingResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.CancelFilingResponse> CancelFilingAsync(FilingHostService.EFMFilingReviewService.CancelFilingRequest request);
        
        // CODEGEN: Generating message contract since element name SecureCaseRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/SecureCase", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/SecureCaseResponse")]
        FilingHostService.EFMFilingReviewService.SecureCaseResponse SecureCase(FilingHostService.EFMFilingReviewService.SecureCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/SecureCase", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/FilingReviewMDEService/SecureCaseResponse")]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.SecureCaseResponse> SecureCaseAsync(FilingHostService.EFMFilingReviewService.SecureCaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReviewFilingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReviewFiling", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.ReviewFilingRequestBody Body;
        
        public ReviewFilingRequest() {
        }
        
        public ReviewFilingRequest(FilingHostService.EFMFilingReviewService.ReviewFilingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class ReviewFilingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ReviewFilingRequest;
        
        public ReviewFilingRequestBody() {
        }
        
        public ReviewFilingRequestBody(System.Xml.Linq.XElement ReviewFilingRequest) {
            this.ReviewFilingRequest = ReviewFilingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReviewFilingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReviewFilingResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.ReviewFilingResponseBody Body;
        
        public ReviewFilingResponse() {
        }
        
        public ReviewFilingResponse(FilingHostService.EFMFilingReviewService.ReviewFilingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class ReviewFilingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ReviewFilingResponse;
        
        public ReviewFilingResponseBody() {
        }
        
        public ReviewFilingResponseBody(System.Xml.Linq.XElement ReviewFilingResponse) {
            this.ReviewFilingResponse = ReviewFilingResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyDocketingCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyDocketingComplete", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequestBody Body;
        
        public NotifyDocketingCompleteRequest() {
        }
        
        public NotifyDocketingCompleteRequest(FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class NotifyDocketingCompleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement NotifyDocketingCompleteRequest;
        
        public NotifyDocketingCompleteRequestBody() {
        }
        
        public NotifyDocketingCompleteRequestBody(System.Xml.Linq.XElement NotifyDocketingCompleteRequest) {
            this.NotifyDocketingCompleteRequest = NotifyDocketingCompleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyDocketingCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyDocketingCompleteResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponseBody Body;
        
        public NotifyDocketingCompleteResponse() {
        }
        
        public NotifyDocketingCompleteResponse(FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class NotifyDocketingCompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement NotifyDocketingCompleteResponse;
        
        public NotifyDocketingCompleteResponseBody() {
        }
        
        public NotifyDocketingCompleteResponseBody(System.Xml.Linq.XElement NotifyDocketingCompleteResponse) {
            this.NotifyDocketingCompleteResponse = NotifyDocketingCompleteResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyCaseAssignmentCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyCaseAssignmentComplete", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequestBody Body;
        
        public NotifyCaseAssignmentCompleteRequest() {
        }
        
        public NotifyCaseAssignmentCompleteRequest(FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class NotifyCaseAssignmentCompleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement NotifyCaseAssignmentCompleteRequest;
        
        public NotifyCaseAssignmentCompleteRequestBody() {
        }
        
        public NotifyCaseAssignmentCompleteRequestBody(System.Xml.Linq.XElement NotifyCaseAssignmentCompleteRequest) {
            this.NotifyCaseAssignmentCompleteRequest = NotifyCaseAssignmentCompleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyCaseAssignmentCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyCaseAssignmentCompleteResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponseBody Body;
        
        public NotifyCaseAssignmentCompleteResponse() {
        }
        
        public NotifyCaseAssignmentCompleteResponse(FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class NotifyCaseAssignmentCompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement NotifyCaseAssignmentCompleteResponse;
        
        public NotifyCaseAssignmentCompleteResponseBody() {
        }
        
        public NotifyCaseAssignmentCompleteResponseBody(System.Xml.Linq.XElement NotifyCaseAssignmentCompleteResponse) {
            this.NotifyCaseAssignmentCompleteResponse = NotifyCaseAssignmentCompleteResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeesCalculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeesCalculation", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFeesCalculationRequestBody Body;
        
        public GetFeesCalculationRequest() {
        }
        
        public GetFeesCalculationRequest(FilingHostService.EFMFilingReviewService.GetFeesCalculationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFeesCalculationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFeesCalculationRequest;
        
        public GetFeesCalculationRequestBody() {
        }
        
        public GetFeesCalculationRequestBody(System.Xml.Linq.XElement GetFeesCalculationRequest) {
            this.GetFeesCalculationRequest = GetFeesCalculationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFeesCalculationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFeesCalculationResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFeesCalculationResponseBody Body;
        
        public GetFeesCalculationResponse() {
        }
        
        public GetFeesCalculationResponse(FilingHostService.EFMFilingReviewService.GetFeesCalculationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFeesCalculationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFeesCalculationResponse;
        
        public GetFeesCalculationResponseBody() {
        }
        
        public GetFeesCalculationResponseBody(System.Xml.Linq.XElement GetFeesCalculationResponse) {
            this.GetFeesCalculationResponse = GetFeesCalculationResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingList", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingListRequestBody Body;
        
        public GetFilingListRequest() {
        }
        
        public GetFilingListRequest(FilingHostService.EFMFilingReviewService.GetFilingListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingListRequest;
        
        public GetFilingListRequestBody() {
        }
        
        public GetFilingListRequestBody(System.Xml.Linq.XElement GetFilingListRequest) {
            this.GetFilingListRequest = GetFilingListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingListResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingListResponseBody Body;
        
        public GetFilingListResponse() {
        }
        
        public GetFilingListResponse(FilingHostService.EFMFilingReviewService.GetFilingListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingListResponse;
        
        public GetFilingListResponseBody() {
        }
        
        public GetFilingListResponseBody(System.Xml.Linq.XElement GetFilingListResponse) {
            this.GetFilingListResponse = GetFilingListResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingStatus", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingStatusRequestBody Body;
        
        public GetFilingStatusRequest() {
        }
        
        public GetFilingStatusRequest(FilingHostService.EFMFilingReviewService.GetFilingStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingStatusRequest;
        
        public GetFilingStatusRequestBody() {
        }
        
        public GetFilingStatusRequestBody(System.Xml.Linq.XElement GetFilingStatusRequest) {
            this.GetFilingStatusRequest = GetFilingStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingStatusResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingStatusResponseBody Body;
        
        public GetFilingStatusResponse() {
        }
        
        public GetFilingStatusResponse(FilingHostService.EFMFilingReviewService.GetFilingStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingStatusResponse;
        
        public GetFilingStatusResponseBody() {
        }
        
        public GetFilingStatusResponseBody(System.Xml.Linq.XElement GetFilingStatusResponse) {
            this.GetFilingStatusResponse = GetFilingStatusResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolicyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPolicy", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetPolicyRequestBody Body;
        
        public GetPolicyRequest() {
        }
        
        public GetPolicyRequest(FilingHostService.EFMFilingReviewService.GetPolicyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetPolicyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetPolicyRequest;
        
        public GetPolicyRequestBody() {
        }
        
        public GetPolicyRequestBody(System.Xml.Linq.XElement GetPolicyRequest) {
            this.GetPolicyRequest = GetPolicyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolicyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPolicyResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetPolicyResponseBody Body;
        
        public GetPolicyResponse() {
        }
        
        public GetPolicyResponse(FilingHostService.EFMFilingReviewService.GetPolicyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetPolicyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetPolicyResponse;
        
        public GetPolicyResponseBody() {
        }
        
        public GetPolicyResponseBody(System.Xml.Linq.XElement GetPolicyResponse) {
            this.GetPolicyResponse = GetPolicyResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingDetails", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingDetailsRequestBody Body;
        
        public GetFilingDetailsRequest() {
        }
        
        public GetFilingDetailsRequest(FilingHostService.EFMFilingReviewService.GetFilingDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingDetailsRequest;
        
        public GetFilingDetailsRequestBody() {
        }
        
        public GetFilingDetailsRequestBody(System.Xml.Linq.XElement GetFilingDetailsRequest) {
            this.GetFilingDetailsRequest = GetFilingDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingDetailsResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingDetailsResponseBody Body;
        
        public GetFilingDetailsResponse() {
        }
        
        public GetFilingDetailsResponse(FilingHostService.EFMFilingReviewService.GetFilingDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingDetailsResponse;
        
        public GetFilingDetailsResponseBody() {
        }
        
        public GetFilingDetailsResponseBody(System.Xml.Linq.XElement GetFilingDetailsResponse) {
            this.GetFilingDetailsResponse = GetFilingDetailsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingService", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingServiceRequestBody Body;
        
        public GetFilingServiceRequest() {
        }
        
        public GetFilingServiceRequest(FilingHostService.EFMFilingReviewService.GetFilingServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingServiceRequest;
        
        public GetFilingServiceRequestBody() {
        }
        
        public GetFilingServiceRequestBody(System.Xml.Linq.XElement GetFilingServiceRequest) {
            this.GetFilingServiceRequest = GetFilingServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingServiceResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.GetFilingServiceResponseBody Body;
        
        public GetFilingServiceResponse() {
        }
        
        public GetFilingServiceResponse(FilingHostService.EFMFilingReviewService.GetFilingServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetFilingServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFilingServiceResponse;
        
        public GetFilingServiceResponseBody() {
        }
        
        public GetFilingServiceResponseBody(System.Xml.Linq.XElement GetFilingServiceResponse) {
            this.GetFilingServiceResponse = GetFilingServiceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelFilingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelFiling", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.CancelFilingRequestBody Body;
        
        public CancelFilingRequest() {
        }
        
        public CancelFilingRequest(FilingHostService.EFMFilingReviewService.CancelFilingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class CancelFilingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CancelFilingRequest;
        
        public CancelFilingRequestBody() {
        }
        
        public CancelFilingRequestBody(System.Xml.Linq.XElement CancelFilingRequest) {
            this.CancelFilingRequest = CancelFilingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelFilingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelFilingResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.CancelFilingResponseBody Body;
        
        public CancelFilingResponse() {
        }
        
        public CancelFilingResponse(FilingHostService.EFMFilingReviewService.CancelFilingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class CancelFilingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CancelFilingResponse;
        
        public CancelFilingResponseBody() {
        }
        
        public CancelFilingResponseBody(System.Xml.Linq.XElement CancelFilingResponse) {
            this.CancelFilingResponse = CancelFilingResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecureCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SecureCase", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.SecureCaseRequestBody Body;
        
        public SecureCaseRequest() {
        }
        
        public SecureCaseRequest(FilingHostService.EFMFilingReviewService.SecureCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class SecureCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SecureCaseRequest;
        
        public SecureCaseRequestBody() {
        }
        
        public SecureCaseRequestBody(System.Xml.Linq.XElement SecureCaseRequest) {
            this.SecureCaseRequest = SecureCaseRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecureCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SecureCaseResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.EFMFilingReviewService.SecureCaseResponseBody Body;
        
        public SecureCaseResponse() {
        }
        
        public SecureCaseResponse(FilingHostService.EFMFilingReviewService.SecureCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class SecureCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SecureCaseResponse;
        
        public SecureCaseResponseBody() {
        }
        
        public SecureCaseResponseBody(System.Xml.Linq.XElement SecureCaseResponse) {
            this.SecureCaseResponse = SecureCaseResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilingReviewMDEServiceChannel : FilingHostService.EFMFilingReviewService.FilingReviewMDEService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilingReviewMDEServiceClient : System.ServiceModel.ClientBase<FilingHostService.EFMFilingReviewService.FilingReviewMDEService>, FilingHostService.EFMFilingReviewService.FilingReviewMDEService {
        
        public FilingReviewMDEServiceClient() {
        }
        
        public FilingReviewMDEServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilingReviewMDEServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilingReviewMDEServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilingReviewMDEServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.ReviewFilingResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.ReviewFiling(FilingHostService.EFMFilingReviewService.ReviewFilingRequest request) {
            return base.Channel.ReviewFiling(request);
        }
        
        public System.Xml.Linq.XElement ReviewFiling(System.Xml.Linq.XElement ReviewFilingRequest) {
            FilingHostService.EFMFilingReviewService.ReviewFilingRequest inValue = new FilingHostService.EFMFilingReviewService.ReviewFilingRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.ReviewFilingRequestBody();
            inValue.Body.ReviewFilingRequest = ReviewFilingRequest;
            FilingHostService.EFMFilingReviewService.ReviewFilingResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).ReviewFiling(inValue);
            return retVal.Body.ReviewFilingResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.ReviewFilingResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.ReviewFilingAsync(FilingHostService.EFMFilingReviewService.ReviewFilingRequest request) {
            return base.Channel.ReviewFilingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.ReviewFilingResponse> ReviewFilingAsync(System.Xml.Linq.XElement ReviewFilingRequest) {
            FilingHostService.EFMFilingReviewService.ReviewFilingRequest inValue = new FilingHostService.EFMFilingReviewService.ReviewFilingRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.ReviewFilingRequestBody();
            inValue.Body.ReviewFilingRequest = ReviewFilingRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).ReviewFilingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.NotifyDocketingComplete(FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest request) {
            return base.Channel.NotifyDocketingComplete(request);
        }
        
        public System.Xml.Linq.XElement NotifyDocketingComplete(System.Xml.Linq.XElement NotifyDocketingCompleteRequest) {
            FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest inValue = new FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequestBody();
            inValue.Body.NotifyDocketingCompleteRequest = NotifyDocketingCompleteRequest;
            FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).NotifyDocketingComplete(inValue);
            return retVal.Body.NotifyDocketingCompleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.NotifyDocketingCompleteAsync(FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest request) {
            return base.Channel.NotifyDocketingCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteResponse> NotifyDocketingCompleteAsync(System.Xml.Linq.XElement NotifyDocketingCompleteRequest) {
            FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest inValue = new FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.NotifyDocketingCompleteRequestBody();
            inValue.Body.NotifyDocketingCompleteRequest = NotifyDocketingCompleteRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).NotifyDocketingCompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.NotifyCaseAssignmentComplete(FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest request) {
            return base.Channel.NotifyCaseAssignmentComplete(request);
        }
        
        public System.Xml.Linq.XElement NotifyCaseAssignmentComplete(System.Xml.Linq.XElement NotifyCaseAssignmentCompleteRequest) {
            FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest inValue = new FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequestBody();
            inValue.Body.NotifyCaseAssignmentCompleteRequest = NotifyCaseAssignmentCompleteRequest;
            FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).NotifyCaseAssignmentComplete(inValue);
            return retVal.Body.NotifyCaseAssignmentCompleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.NotifyCaseAssignmentCompleteAsync(FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest request) {
            return base.Channel.NotifyCaseAssignmentCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteResponse> NotifyCaseAssignmentCompleteAsync(System.Xml.Linq.XElement NotifyCaseAssignmentCompleteRequest) {
            FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest inValue = new FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.NotifyCaseAssignmentCompleteRequestBody();
            inValue.Body.NotifyCaseAssignmentCompleteRequest = NotifyCaseAssignmentCompleteRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).NotifyCaseAssignmentCompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.GetFeesCalculationResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFeesCalculation(FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest request) {
            return base.Channel.GetFeesCalculation(request);
        }
        
        public System.Xml.Linq.XElement GetFeesCalculation(System.Xml.Linq.XElement GetFeesCalculationRequest) {
            FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest inValue = new FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFeesCalculationRequestBody();
            inValue.Body.GetFeesCalculationRequest = GetFeesCalculationRequest;
            FilingHostService.EFMFilingReviewService.GetFeesCalculationResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFeesCalculation(inValue);
            return retVal.Body.GetFeesCalculationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFeesCalculationResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFeesCalculationAsync(FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest request) {
            return base.Channel.GetFeesCalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFeesCalculationResponse> GetFeesCalculationAsync(System.Xml.Linq.XElement GetFeesCalculationRequest) {
            FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest inValue = new FilingHostService.EFMFilingReviewService.GetFeesCalculationRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFeesCalculationRequestBody();
            inValue.Body.GetFeesCalculationRequest = GetFeesCalculationRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFeesCalculationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.GetFilingListResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingList(FilingHostService.EFMFilingReviewService.GetFilingListRequest request) {
            return base.Channel.GetFilingList(request);
        }
        
        public System.Xml.Linq.XElement GetFilingList(System.Xml.Linq.XElement GetFilingListRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingListRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingListRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingListRequestBody();
            inValue.Body.GetFilingListRequest = GetFilingListRequest;
            FilingHostService.EFMFilingReviewService.GetFilingListResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingList(inValue);
            return retVal.Body.GetFilingListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingListResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingListAsync(FilingHostService.EFMFilingReviewService.GetFilingListRequest request) {
            return base.Channel.GetFilingListAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingListResponse> GetFilingListAsync(System.Xml.Linq.XElement GetFilingListRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingListRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingListRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingListRequestBody();
            inValue.Body.GetFilingListRequest = GetFilingListRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.GetFilingStatusResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingStatus(FilingHostService.EFMFilingReviewService.GetFilingStatusRequest request) {
            return base.Channel.GetFilingStatus(request);
        }
        
        public System.Xml.Linq.XElement GetFilingStatus(System.Xml.Linq.XElement GetFilingStatusRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingStatusRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingStatusRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingStatusRequestBody();
            inValue.Body.GetFilingStatusRequest = GetFilingStatusRequest;
            FilingHostService.EFMFilingReviewService.GetFilingStatusResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingStatus(inValue);
            return retVal.Body.GetFilingStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingStatusResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingStatusAsync(FilingHostService.EFMFilingReviewService.GetFilingStatusRequest request) {
            return base.Channel.GetFilingStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingStatusResponse> GetFilingStatusAsync(System.Xml.Linq.XElement GetFilingStatusRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingStatusRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingStatusRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingStatusRequestBody();
            inValue.Body.GetFilingStatusRequest = GetFilingStatusRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.GetPolicyResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetPolicy(FilingHostService.EFMFilingReviewService.GetPolicyRequest request) {
            return base.Channel.GetPolicy(request);
        }
        
        public System.Xml.Linq.XElement GetPolicy(System.Xml.Linq.XElement GetPolicyRequest) {
            FilingHostService.EFMFilingReviewService.GetPolicyRequest inValue = new FilingHostService.EFMFilingReviewService.GetPolicyRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetPolicyRequestBody();
            inValue.Body.GetPolicyRequest = GetPolicyRequest;
            FilingHostService.EFMFilingReviewService.GetPolicyResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetPolicy(inValue);
            return retVal.Body.GetPolicyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetPolicyResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetPolicyAsync(FilingHostService.EFMFilingReviewService.GetPolicyRequest request) {
            return base.Channel.GetPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetPolicyResponse> GetPolicyAsync(System.Xml.Linq.XElement GetPolicyRequest) {
            FilingHostService.EFMFilingReviewService.GetPolicyRequest inValue = new FilingHostService.EFMFilingReviewService.GetPolicyRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetPolicyRequestBody();
            inValue.Body.GetPolicyRequest = GetPolicyRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetPolicyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.GetFilingDetailsResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingDetails(FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest request) {
            return base.Channel.GetFilingDetails(request);
        }
        
        public System.Xml.Linq.XElement GetFilingDetails(System.Xml.Linq.XElement GetFilingDetailsRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingDetailsRequestBody();
            inValue.Body.GetFilingDetailsRequest = GetFilingDetailsRequest;
            FilingHostService.EFMFilingReviewService.GetFilingDetailsResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingDetails(inValue);
            return retVal.Body.GetFilingDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingDetailsResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingDetailsAsync(FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest request) {
            return base.Channel.GetFilingDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingDetailsResponse> GetFilingDetailsAsync(System.Xml.Linq.XElement GetFilingDetailsRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingDetailsRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingDetailsRequestBody();
            inValue.Body.GetFilingDetailsRequest = GetFilingDetailsRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.GetFilingServiceResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingService(FilingHostService.EFMFilingReviewService.GetFilingServiceRequest request) {
            return base.Channel.GetFilingService(request);
        }
        
        public System.Xml.Linq.XElement GetFilingService(System.Xml.Linq.XElement GetFilingServiceRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingServiceRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingServiceRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingServiceRequestBody();
            inValue.Body.GetFilingServiceRequest = GetFilingServiceRequest;
            FilingHostService.EFMFilingReviewService.GetFilingServiceResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingService(inValue);
            return retVal.Body.GetFilingServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingServiceResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.GetFilingServiceAsync(FilingHostService.EFMFilingReviewService.GetFilingServiceRequest request) {
            return base.Channel.GetFilingServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.GetFilingServiceResponse> GetFilingServiceAsync(System.Xml.Linq.XElement GetFilingServiceRequest) {
            FilingHostService.EFMFilingReviewService.GetFilingServiceRequest inValue = new FilingHostService.EFMFilingReviewService.GetFilingServiceRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.GetFilingServiceRequestBody();
            inValue.Body.GetFilingServiceRequest = GetFilingServiceRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).GetFilingServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.CancelFilingResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.CancelFiling(FilingHostService.EFMFilingReviewService.CancelFilingRequest request) {
            return base.Channel.CancelFiling(request);
        }
        
        public System.Xml.Linq.XElement CancelFiling(System.Xml.Linq.XElement CancelFilingRequest) {
            FilingHostService.EFMFilingReviewService.CancelFilingRequest inValue = new FilingHostService.EFMFilingReviewService.CancelFilingRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.CancelFilingRequestBody();
            inValue.Body.CancelFilingRequest = CancelFilingRequest;
            FilingHostService.EFMFilingReviewService.CancelFilingResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).CancelFiling(inValue);
            return retVal.Body.CancelFilingResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.CancelFilingResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.CancelFilingAsync(FilingHostService.EFMFilingReviewService.CancelFilingRequest request) {
            return base.Channel.CancelFilingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.CancelFilingResponse> CancelFilingAsync(System.Xml.Linq.XElement CancelFilingRequest) {
            FilingHostService.EFMFilingReviewService.CancelFilingRequest inValue = new FilingHostService.EFMFilingReviewService.CancelFilingRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.CancelFilingRequestBody();
            inValue.Body.CancelFilingRequest = CancelFilingRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).CancelFilingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.EFMFilingReviewService.SecureCaseResponse FilingHostService.EFMFilingReviewService.FilingReviewMDEService.SecureCase(FilingHostService.EFMFilingReviewService.SecureCaseRequest request) {
            return base.Channel.SecureCase(request);
        }
        
        public System.Xml.Linq.XElement SecureCase(System.Xml.Linq.XElement SecureCaseRequest) {
            FilingHostService.EFMFilingReviewService.SecureCaseRequest inValue = new FilingHostService.EFMFilingReviewService.SecureCaseRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.SecureCaseRequestBody();
            inValue.Body.SecureCaseRequest = SecureCaseRequest;
            FilingHostService.EFMFilingReviewService.SecureCaseResponse retVal = ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).SecureCase(inValue);
            return retVal.Body.SecureCaseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.SecureCaseResponse> FilingHostService.EFMFilingReviewService.FilingReviewMDEService.SecureCaseAsync(FilingHostService.EFMFilingReviewService.SecureCaseRequest request) {
            return base.Channel.SecureCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.EFMFilingReviewService.SecureCaseResponse> SecureCaseAsync(System.Xml.Linq.XElement SecureCaseRequest) {
            FilingHostService.EFMFilingReviewService.SecureCaseRequest inValue = new FilingHostService.EFMFilingReviewService.SecureCaseRequest();
            inValue.Body = new FilingHostService.EFMFilingReviewService.SecureCaseRequestBody();
            inValue.Body.SecureCaseRequest = SecureCaseRequest;
            return ((FilingHostService.EFMFilingReviewService.FilingReviewMDEService)(this)).SecureCaseAsync(inValue);
        }
    }
}
