//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilingHostService.CourtRecordMDEService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0", ConfigurationName="CourtRecordMDEService.CourtRecordMDEService")]
    public interface CourtRecordMDEService {
        
        // CODEGEN: Generating message contract since element name RecordFilingRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/RecordFiling", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/RecordFilingResponse")]
        FilingHostService.CourtRecordMDEService.RecordFilingResponse RecordFiling(FilingHostService.CourtRecordMDEService.RecordFilingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/RecordFiling", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/RecordFilingResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.RecordFilingResponse> RecordFilingAsync(FilingHostService.CourtRecordMDEService.RecordFilingRequest request);
        
        // CODEGEN: Generating message contract since element name CreateCaseRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/CreateCase", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/CreateCaseResponse")]
        FilingHostService.CourtRecordMDEService.CreateCaseResponse CreateCase(FilingHostService.CourtRecordMDEService.CreateCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/CreateCase", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/CreateCaseResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.CreateCaseResponse> CreateCaseAsync(FilingHostService.CourtRecordMDEService.CreateCaseRequest request);
        
        // CODEGEN: Generating message contract since element name GetCaseListRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCaseList", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCaseListResponse")]
        FilingHostService.CourtRecordMDEService.GetCaseListResponse GetCaseList(FilingHostService.CourtRecordMDEService.GetCaseListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCaseList", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCaseListResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetCaseListResponse> GetCaseListAsync(FilingHostService.CourtRecordMDEService.GetCaseListRequest request);
        
        // CODEGEN: Generating message contract since element name GetCaseRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCase", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCaseResponse")]
        FilingHostService.CourtRecordMDEService.GetCaseResponse GetCase(FilingHostService.CourtRecordMDEService.GetCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCase", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetCaseResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetCaseResponse> GetCaseAsync(FilingHostService.CourtRecordMDEService.GetCaseRequest request);
        
        // CODEGEN: Generating message contract since element name GetDocumentRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetDocument", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetDocumentResponse")]
        FilingHostService.CourtRecordMDEService.GetDocumentResponse GetDocument(FilingHostService.CourtRecordMDEService.GetDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetDocument", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetDocumentResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetDocumentResponse> GetDocumentAsync(FilingHostService.CourtRecordMDEService.GetDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name GetServiceInformationRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformation", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformationResponse")]
        FilingHostService.CourtRecordMDEService.GetServiceInformationResponse GetServiceInformation(FilingHostService.CourtRecordMDEService.GetServiceInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformation", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformationResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceInformationResponse> GetServiceInformationAsync(FilingHostService.CourtRecordMDEService.GetServiceInformationRequest request);
        
        // CODEGEN: Generating message contract since element name GetServiceInformationHistoryRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformationHistory", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformationHistoryResponse")]
        FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponse GetServiceInformationHistory(FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformationHistory", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceInformationHistoryResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponse> GetServiceInformationHistoryAsync(FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetServiceAttachCaseListRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceAttachCaseList", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceAttachCaseListResponse")]
        FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponse GetServiceAttachCaseList(FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceAttachCaseList", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/GetServiceAttachCaseListResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponse> GetServiceAttachCaseListAsync(FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest request);
        
        // CODEGEN: Generating message contract since element name NotifyReceiptCompleteRequest from namespace urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitions-4.0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/NotifyReceiptComplete", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/NotifyReceiptCompleteResponse")]
        FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponse NotifyReceiptComplete(FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/NotifyReceiptComplete", ReplyAction="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0/CourtRecordMDEService/NotifyReceiptCompleteResponse")]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponse> NotifyReceiptCompleteAsync(FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordFilingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecordFiling", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.RecordFilingRequestBody Body;
        
        public RecordFilingRequest() {
        }
        
        public RecordFilingRequest(FilingHostService.CourtRecordMDEService.RecordFilingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class RecordFilingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RecordFilingRequest;
        
        public RecordFilingRequestBody() {
        }
        
        public RecordFilingRequestBody(System.Xml.Linq.XElement RecordFilingRequest) {
            this.RecordFilingRequest = RecordFilingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordFilingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecordFilingResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.RecordFilingResponseBody Body;
        
        public RecordFilingResponse() {
        }
        
        public RecordFilingResponse(FilingHostService.CourtRecordMDEService.RecordFilingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class RecordFilingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RecordFilingResponseMessage;
        
        public RecordFilingResponseBody() {
        }
        
        public RecordFilingResponseBody(System.Xml.Linq.XElement RecordFilingResponseMessage) {
            this.RecordFilingResponseMessage = RecordFilingResponseMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCase", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.CreateCaseRequestBody Body;
        
        public CreateCaseRequest() {
        }
        
        public CreateCaseRequest(FilingHostService.CourtRecordMDEService.CreateCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class CreateCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CreateCaseRequest;
        
        public CreateCaseRequestBody() {
        }
        
        public CreateCaseRequestBody(System.Xml.Linq.XElement CreateCaseRequest) {
            this.CreateCaseRequest = CreateCaseRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCaseResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.CreateCaseResponseBody Body;
        
        public CreateCaseResponse() {
        }
        
        public CreateCaseResponse(FilingHostService.CourtRecordMDEService.CreateCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class CreateCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CreateCaseResponse;
        
        public CreateCaseResponseBody() {
        }
        
        public CreateCaseResponseBody(System.Xml.Linq.XElement CreateCaseResponse) {
            this.CreateCaseResponse = CreateCaseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCaseListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCaseList", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetCaseListRequestBody Body;
        
        public GetCaseListRequest() {
        }
        
        public GetCaseListRequest(FilingHostService.CourtRecordMDEService.GetCaseListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetCaseListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCaseListRequest;
        
        public GetCaseListRequestBody() {
        }
        
        public GetCaseListRequestBody(System.Xml.Linq.XElement GetCaseListRequest) {
            this.GetCaseListRequest = GetCaseListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCaseListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCaseListResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetCaseListResponseBody Body;
        
        public GetCaseListResponse() {
        }
        
        public GetCaseListResponse(FilingHostService.CourtRecordMDEService.GetCaseListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetCaseListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCaseListResponse;
        
        public GetCaseListResponseBody() {
        }
        
        public GetCaseListResponseBody(System.Xml.Linq.XElement GetCaseListResponse) {
            this.GetCaseListResponse = GetCaseListResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCase", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetCaseRequestBody Body;
        
        public GetCaseRequest() {
        }
        
        public GetCaseRequest(FilingHostService.CourtRecordMDEService.GetCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCaseRequest;
        
        public GetCaseRequestBody() {
        }
        
        public GetCaseRequestBody(System.Xml.Linq.XElement GetCaseRequest) {
            this.GetCaseRequest = GetCaseRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCaseResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetCaseResponseBody Body;
        
        public GetCaseResponse() {
        }
        
        public GetCaseResponse(FilingHostService.CourtRecordMDEService.GetCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCaseResponse;
        
        public GetCaseResponseBody() {
        }
        
        public GetCaseResponseBody(System.Xml.Linq.XElement GetCaseResponse) {
            this.GetCaseResponse = GetCaseResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocument", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetDocumentRequestBody Body;
        
        public GetDocumentRequest() {
        }
        
        public GetDocumentRequest(FilingHostService.CourtRecordMDEService.GetDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDocumentRequest;
        
        public GetDocumentRequestBody() {
        }
        
        public GetDocumentRequestBody(System.Xml.Linq.XElement GetDocumentRequest) {
            this.GetDocumentRequest = GetDocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetDocumentResponseBody Body;
        
        public GetDocumentResponse() {
        }
        
        public GetDocumentResponse(FilingHostService.CourtRecordMDEService.GetDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDocumentResponse;
        
        public GetDocumentResponseBody() {
        }
        
        public GetDocumentResponseBody(System.Xml.Linq.XElement GetDocumentResponse) {
            this.GetDocumentResponse = GetDocumentResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceInformation", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetServiceInformationRequestBody Body;
        
        public GetServiceInformationRequest() {
        }
        
        public GetServiceInformationRequest(FilingHostService.CourtRecordMDEService.GetServiceInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetServiceInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetServiceInformationRequest;
        
        public GetServiceInformationRequestBody() {
        }
        
        public GetServiceInformationRequestBody(System.Xml.Linq.XElement GetServiceInformationRequest) {
            this.GetServiceInformationRequest = GetServiceInformationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceInformationResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetServiceInformationResponseBody Body;
        
        public GetServiceInformationResponse() {
        }
        
        public GetServiceInformationResponse(FilingHostService.CourtRecordMDEService.GetServiceInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetServiceInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetServiceInformationResponse;
        
        public GetServiceInformationResponseBody() {
        }
        
        public GetServiceInformationResponseBody(System.Xml.Linq.XElement GetServiceInformationResponse) {
            this.GetServiceInformationResponse = GetServiceInformationResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceInformationHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceInformationHistory", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequestBody Body;
        
        public GetServiceInformationHistoryRequest() {
        }
        
        public GetServiceInformationHistoryRequest(FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetServiceInformationHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetServiceInformationHistoryRequest;
        
        public GetServiceInformationHistoryRequestBody() {
        }
        
        public GetServiceInformationHistoryRequestBody(System.Xml.Linq.XElement GetServiceInformationHistoryRequest) {
            this.GetServiceInformationHistoryRequest = GetServiceInformationHistoryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceInformationHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceInformationHistoryResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponseBody Body;
        
        public GetServiceInformationHistoryResponse() {
        }
        
        public GetServiceInformationHistoryResponse(FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetServiceInformationHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetServiceInformationHistoryResponse;
        
        public GetServiceInformationHistoryResponseBody() {
        }
        
        public GetServiceInformationHistoryResponseBody(System.Xml.Linq.XElement GetServiceInformationHistoryResponse) {
            this.GetServiceInformationHistoryResponse = GetServiceInformationHistoryResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceAttachCaseListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceAttachCaseList", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequestBody Body;
        
        public GetServiceAttachCaseListRequest() {
        }
        
        public GetServiceAttachCaseListRequest(FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetServiceAttachCaseListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetServiceAttachCaseListRequest;
        
        public GetServiceAttachCaseListRequestBody() {
        }
        
        public GetServiceAttachCaseListRequestBody(System.Xml.Linq.XElement GetServiceAttachCaseListRequest) {
            this.GetServiceAttachCaseListRequest = GetServiceAttachCaseListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceAttachCaseListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceAttachCaseListResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponseBody Body;
        
        public GetServiceAttachCaseListResponse() {
        }
        
        public GetServiceAttachCaseListResponse(FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class GetServiceAttachCaseListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetServiceAttachCaseListResponse;
        
        public GetServiceAttachCaseListResponseBody() {
        }
        
        public GetServiceAttachCaseListResponseBody(System.Xml.Linq.XElement GetServiceAttachCaseListResponse) {
            this.GetServiceAttachCaseListResponse = GetServiceAttachCaseListResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyReceiptCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyReceiptComplete", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequestBody Body;
        
        public NotifyReceiptCompleteRequest() {
        }
        
        public NotifyReceiptCompleteRequest(FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class NotifyReceiptCompleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement NotifyReceiptCompleteRequest;
        
        public NotifyReceiptCompleteRequestBody() {
        }
        
        public NotifyReceiptCompleteRequestBody(System.Xml.Linq.XElement NotifyReceiptCompleteRequest) {
            this.NotifyReceiptCompleteRequest = NotifyReceiptCompleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyReceiptCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyReceiptCompleteResponse", Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
            "ns-4.0", Order=0)]
        public FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponseBody Body;
        
        public NotifyReceiptCompleteResponse() {
        }
        
        public NotifyReceiptCompleteResponse(FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServiceMessagingProfile-Definitio" +
        "ns-4.0")]
    public partial class NotifyReceiptCompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement NotifyReceiptCompleteResponse;
        
        public NotifyReceiptCompleteResponseBody() {
        }
        
        public NotifyReceiptCompleteResponseBody(System.Xml.Linq.XElement NotifyReceiptCompleteResponse) {
            this.NotifyReceiptCompleteResponse = NotifyReceiptCompleteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CourtRecordMDEServiceChannel : FilingHostService.CourtRecordMDEService.CourtRecordMDEService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourtRecordMDEServiceClient : System.ServiceModel.ClientBase<FilingHostService.CourtRecordMDEService.CourtRecordMDEService>, FilingHostService.CourtRecordMDEService.CourtRecordMDEService {
        
        public CourtRecordMDEServiceClient() {
        }
        
        public CourtRecordMDEServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourtRecordMDEServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourtRecordMDEServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourtRecordMDEServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.RecordFilingResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.RecordFiling(FilingHostService.CourtRecordMDEService.RecordFilingRequest request) {
            return base.Channel.RecordFiling(request);
        }
        
        public System.Xml.Linq.XElement RecordFiling(System.Xml.Linq.XElement RecordFilingRequest) {
            FilingHostService.CourtRecordMDEService.RecordFilingRequest inValue = new FilingHostService.CourtRecordMDEService.RecordFilingRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.RecordFilingRequestBody();
            inValue.Body.RecordFilingRequest = RecordFilingRequest;
            FilingHostService.CourtRecordMDEService.RecordFilingResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).RecordFiling(inValue);
            return retVal.Body.RecordFilingResponseMessage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.RecordFilingResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.RecordFilingAsync(FilingHostService.CourtRecordMDEService.RecordFilingRequest request) {
            return base.Channel.RecordFilingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.RecordFilingResponse> RecordFilingAsync(System.Xml.Linq.XElement RecordFilingRequest) {
            FilingHostService.CourtRecordMDEService.RecordFilingRequest inValue = new FilingHostService.CourtRecordMDEService.RecordFilingRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.RecordFilingRequestBody();
            inValue.Body.RecordFilingRequest = RecordFilingRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).RecordFilingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.CreateCaseResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.CreateCase(FilingHostService.CourtRecordMDEService.CreateCaseRequest request) {
            return base.Channel.CreateCase(request);
        }
        
        public System.Xml.Linq.XElement CreateCase(System.Xml.Linq.XElement CreateCaseRequest) {
            FilingHostService.CourtRecordMDEService.CreateCaseRequest inValue = new FilingHostService.CourtRecordMDEService.CreateCaseRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.CreateCaseRequestBody();
            inValue.Body.CreateCaseRequest = CreateCaseRequest;
            FilingHostService.CourtRecordMDEService.CreateCaseResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).CreateCase(inValue);
            return retVal.Body.CreateCaseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.CreateCaseResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.CreateCaseAsync(FilingHostService.CourtRecordMDEService.CreateCaseRequest request) {
            return base.Channel.CreateCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.CreateCaseResponse> CreateCaseAsync(System.Xml.Linq.XElement CreateCaseRequest) {
            FilingHostService.CourtRecordMDEService.CreateCaseRequest inValue = new FilingHostService.CourtRecordMDEService.CreateCaseRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.CreateCaseRequestBody();
            inValue.Body.CreateCaseRequest = CreateCaseRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).CreateCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.GetCaseListResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetCaseList(FilingHostService.CourtRecordMDEService.GetCaseListRequest request) {
            return base.Channel.GetCaseList(request);
        }
        
        public System.Xml.Linq.XElement GetCaseList(System.Xml.Linq.XElement GetCaseListRequest) {
            FilingHostService.CourtRecordMDEService.GetCaseListRequest inValue = new FilingHostService.CourtRecordMDEService.GetCaseListRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetCaseListRequestBody();
            inValue.Body.GetCaseListRequest = GetCaseListRequest;
            FilingHostService.CourtRecordMDEService.GetCaseListResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetCaseList(inValue);
            return retVal.Body.GetCaseListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetCaseListResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetCaseListAsync(FilingHostService.CourtRecordMDEService.GetCaseListRequest request) {
            return base.Channel.GetCaseListAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetCaseListResponse> GetCaseListAsync(System.Xml.Linq.XElement GetCaseListRequest) {
            FilingHostService.CourtRecordMDEService.GetCaseListRequest inValue = new FilingHostService.CourtRecordMDEService.GetCaseListRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetCaseListRequestBody();
            inValue.Body.GetCaseListRequest = GetCaseListRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetCaseListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.GetCaseResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetCase(FilingHostService.CourtRecordMDEService.GetCaseRequest request) {
            return base.Channel.GetCase(request);
        }
        
        public System.Xml.Linq.XElement GetCase(System.Xml.Linq.XElement GetCaseRequest) {
            FilingHostService.CourtRecordMDEService.GetCaseRequest inValue = new FilingHostService.CourtRecordMDEService.GetCaseRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetCaseRequestBody();
            inValue.Body.GetCaseRequest = GetCaseRequest;
            FilingHostService.CourtRecordMDEService.GetCaseResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetCase(inValue);
            return retVal.Body.GetCaseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetCaseResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetCaseAsync(FilingHostService.CourtRecordMDEService.GetCaseRequest request) {
            return base.Channel.GetCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetCaseResponse> GetCaseAsync(System.Xml.Linq.XElement GetCaseRequest) {
            FilingHostService.CourtRecordMDEService.GetCaseRequest inValue = new FilingHostService.CourtRecordMDEService.GetCaseRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetCaseRequestBody();
            inValue.Body.GetCaseRequest = GetCaseRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.GetDocumentResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetDocument(FilingHostService.CourtRecordMDEService.GetDocumentRequest request) {
            return base.Channel.GetDocument(request);
        }
        
        public System.Xml.Linq.XElement GetDocument(System.Xml.Linq.XElement GetDocumentRequest) {
            FilingHostService.CourtRecordMDEService.GetDocumentRequest inValue = new FilingHostService.CourtRecordMDEService.GetDocumentRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetDocumentRequestBody();
            inValue.Body.GetDocumentRequest = GetDocumentRequest;
            FilingHostService.CourtRecordMDEService.GetDocumentResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetDocument(inValue);
            return retVal.Body.GetDocumentResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetDocumentResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetDocumentAsync(FilingHostService.CourtRecordMDEService.GetDocumentRequest request) {
            return base.Channel.GetDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetDocumentResponse> GetDocumentAsync(System.Xml.Linq.XElement GetDocumentRequest) {
            FilingHostService.CourtRecordMDEService.GetDocumentRequest inValue = new FilingHostService.CourtRecordMDEService.GetDocumentRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetDocumentRequestBody();
            inValue.Body.GetDocumentRequest = GetDocumentRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.GetServiceInformationResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetServiceInformation(FilingHostService.CourtRecordMDEService.GetServiceInformationRequest request) {
            return base.Channel.GetServiceInformation(request);
        }
        
        public System.Xml.Linq.XElement GetServiceInformation(System.Xml.Linq.XElement GetServiceInformationRequest) {
            FilingHostService.CourtRecordMDEService.GetServiceInformationRequest inValue = new FilingHostService.CourtRecordMDEService.GetServiceInformationRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetServiceInformationRequestBody();
            inValue.Body.GetServiceInformationRequest = GetServiceInformationRequest;
            FilingHostService.CourtRecordMDEService.GetServiceInformationResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetServiceInformation(inValue);
            return retVal.Body.GetServiceInformationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceInformationResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetServiceInformationAsync(FilingHostService.CourtRecordMDEService.GetServiceInformationRequest request) {
            return base.Channel.GetServiceInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceInformationResponse> GetServiceInformationAsync(System.Xml.Linq.XElement GetServiceInformationRequest) {
            FilingHostService.CourtRecordMDEService.GetServiceInformationRequest inValue = new FilingHostService.CourtRecordMDEService.GetServiceInformationRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetServiceInformationRequestBody();
            inValue.Body.GetServiceInformationRequest = GetServiceInformationRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetServiceInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetServiceInformationHistory(FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest request) {
            return base.Channel.GetServiceInformationHistory(request);
        }
        
        public System.Xml.Linq.XElement GetServiceInformationHistory(System.Xml.Linq.XElement GetServiceInformationHistoryRequest) {
            FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest inValue = new FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequestBody();
            inValue.Body.GetServiceInformationHistoryRequest = GetServiceInformationHistoryRequest;
            FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetServiceInformationHistory(inValue);
            return retVal.Body.GetServiceInformationHistoryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetServiceInformationHistoryAsync(FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest request) {
            return base.Channel.GetServiceInformationHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryResponse> GetServiceInformationHistoryAsync(System.Xml.Linq.XElement GetServiceInformationHistoryRequest) {
            FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest inValue = new FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetServiceInformationHistoryRequestBody();
            inValue.Body.GetServiceInformationHistoryRequest = GetServiceInformationHistoryRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetServiceInformationHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetServiceAttachCaseList(FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest request) {
            return base.Channel.GetServiceAttachCaseList(request);
        }
        
        public System.Xml.Linq.XElement GetServiceAttachCaseList(System.Xml.Linq.XElement GetServiceAttachCaseListRequest) {
            FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest inValue = new FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequestBody();
            inValue.Body.GetServiceAttachCaseListRequest = GetServiceAttachCaseListRequest;
            FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetServiceAttachCaseList(inValue);
            return retVal.Body.GetServiceAttachCaseListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.GetServiceAttachCaseListAsync(FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest request) {
            return base.Channel.GetServiceAttachCaseListAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListResponse> GetServiceAttachCaseListAsync(System.Xml.Linq.XElement GetServiceAttachCaseListRequest) {
            FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest inValue = new FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.GetServiceAttachCaseListRequestBody();
            inValue.Body.GetServiceAttachCaseListRequest = GetServiceAttachCaseListRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).GetServiceAttachCaseListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponse FilingHostService.CourtRecordMDEService.CourtRecordMDEService.NotifyReceiptComplete(FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest request) {
            return base.Channel.NotifyReceiptComplete(request);
        }
        
        public System.Xml.Linq.XElement NotifyReceiptComplete(System.Xml.Linq.XElement NotifyReceiptCompleteRequest) {
            FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest inValue = new FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequestBody();
            inValue.Body.NotifyReceiptCompleteRequest = NotifyReceiptCompleteRequest;
            FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponse retVal = ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).NotifyReceiptComplete(inValue);
            return retVal.Body.NotifyReceiptCompleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponse> FilingHostService.CourtRecordMDEService.CourtRecordMDEService.NotifyReceiptCompleteAsync(FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest request) {
            return base.Channel.NotifyReceiptCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteResponse> NotifyReceiptCompleteAsync(System.Xml.Linq.XElement NotifyReceiptCompleteRequest) {
            FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest inValue = new FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequest();
            inValue.Body = new FilingHostService.CourtRecordMDEService.NotifyReceiptCompleteRequestBody();
            inValue.Body.NotifyReceiptCompleteRequest = NotifyReceiptCompleteRequest;
            return ((FilingHostService.CourtRecordMDEService.CourtRecordMDEService)(this)).NotifyReceiptCompleteAsync(inValue);
        }
    }
}
